server:
  port: 8014
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardcore_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com.hardcore.accounting: DEBUG